import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import ReactQueryProvider from "@/providers/QueryClientProvider";
import LayoutProvider from "@/providers/LayoutProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({ subsets: ["latin"], weight: "400", display: "swap" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      className="light"
      style={{ colorScheme: "light" }}
    >
      {/* Put generated favicons meta in the head */}
      <head></head>
      <body
        className={poppins.className}
        style={{
          colorScheme: "light",
          backgroundColor: "var(--background)",
          color: "var(--text)",
        }}
        suppressHydrationWarning
      >
        <ThemeProvider>
          <ReactQueryProvider>
            <LayoutProvider>{children}</LayoutProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
